### ISSUE TITLE
Regex not triggering

### ISSUE THREAD

**Issue by geekscrapy** [RobberPhex/iterm2-zmodem#1]
Hi, I implemented your tool as your instructions but it seems like iTerm isn't picking up the Triggers regex, are they correct? I would have thought it's be more like: `rz` or `sz` ?

As if you issue `rz` on the remote machine it comes back with command not found.

iTerm2 Build 3.3.6
OSX 10.14.6

Thanks!

**Comment by robberphex** [comment]
The prerequisite is that `rz` is installed at remote machine, if you want to upload file to remote machine.

**Comment by KeithTt** [comment]
```
/usr/local/bin/iterm2-send-zmodem.sh: line 21: /usr/local/bin/sz: No such file or directory
```

Similar problem, it is normal in my old MBP, but not work in the new one.

iTerm2 Build 3.4.16
macOS Monterey 12.4

**Comment by robberphex** [comment]
Could you install lrzsz, by `brew install lrzsz`, and try again?

**Comment by KeithTt** [comment]
@robberphex Thank you for reminding.

I tried to reinstall `lrzsz`
```
$ brew reinstall lrzsz
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/lrzsz-0.12.20_1.arm64_monterey.bottle.tar.gz
Already downloaded: /Users/shengyong.pei/Library/Caches/Homebrew/downloads/55cc0cc43a1d5437503ae16fe573e2515fd67d1c8e5990c67ae83199c71ea550--lrzsz-0.12.20_1.arm64_monterey.bottle.tar.gz
==> Reinstalling lrzsz
==> Pouring lrzsz-0.12.20_1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/lrzsz/0.12.20_1: 18 files, 656.5KB
==> Running `brew cleanup lrzsz`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

And found the binaries are in `/opt/homebrew/Cellar/lrzsz/0.12.20_1/bin`, then I copy them to `/usr/local/bin`
```
sudo cp -a lsz /usr/local/bin/sz
sudo cp -a lrz /usr/local/bin/rz
```

Then it works. Thanks a lot.
